### ISSUE TITLE
Line not compiling with Java 8

### ISSUE THREAD

**Issue by adidascodingchallenge** [thiago123789/code-challenge#1]
Could you check this line? It's failing when compiling using java 8 with `package com.sun.javafx.collections does not exist`

https://github.com/thiago123789/code-challenge/blob/8554e78aafab7662f5d201eb72c0c3c94b785939/bff/src/main/java/code/challenge/bff/config/SwaggerUiConfig.java#L3

**Comment by thiago123789** [comment]
@adidascodingchallenge I just pushed a commit to remove the unused imports. this specific line was one of them.
